# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19e231fdd92c47b465732a5907b484235daa8a5b9b643d7fac6826f892016b6c0c16b66ccbc75e05dbadc516b82ef21f59d9e799b94c9ec99f0516fc6a119acc

test:
  secret_key_base: 044cb479a5671449c3bf49b720f9805e6556a9052afea4cf198365dd5e41dccb0e4a7fe918850e23daf9ad82d1520675f7afa072c3d4674c8857179e784ece46

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
